DROP TABLE IF EXISTS kpis;
DROP TABLE IF EXISTS locations;
DROP TABLE IF EXISTS rules;
DROP TABLE IF EXISTS alerts;
DROP TABLE IF EXISTS failed_kpis;
DROP TABLE IF EXISTS kpi_threshold;


create table kpis
(
    id            integer                           not null primary key,
    "phase"       text COLLATE pg_catalog."default",
    "session_id"  text COLLATE pg_catalog."default" not null,
    "timestamp"   integer,
    "failed"      boolean,
    "location_id" integer,
    "latency"     double precision
);

create table locations
(
    id     integer not null primary key,
    "code" text COLLATE pg_catalog."default"
);

create table rules
(
    id                 integer not null primary key,
    "content"          text COLLATE pg_catalog."default",
    "create_time"      text COLLATE pg_catalog."default",
    "last_modify_time" text COLLATE pg_catalog."default",
    "rule_key"         text COLLATE pg_catalog."default",
    "version"          text COLLATE pg_catalog."default"
);

create table alerts
(
    id                 integer not null primary key,
    "agent_id"          text COLLATE pg_catalog."default",
    "alert_id"          text COLLATE pg_catalog."default",
    "agent_test_name"    text COLLATE pg_catalog."default",
    "test_session_id"    text COLLATE pg_catalog."default",
    "test_id"           text COLLATE pg_catalog."default",
    "agent_test_id"      text COLLATE pg_catalog."default",
    "workflow_id"       text COLLATE pg_catalog."default",
    "overlay_id"        text COLLATE pg_catalog."default",
    "network_element_id" text COLLATE pg_catalog."default",
    "category"         text COLLATE pg_catalog."default",
    "package"          text COLLATE pg_catalog."default",
    "test_name"             text COLLATE pg_catalog."default",
    "alert_name"             text COLLATE pg_catalog."default",
    "level"            text COLLATE pg_catalog."default",
    "timestamp"        text COLLATE pg_catalog."default",
    CONSTRAINT alert_id_unique UNIQUE ("alert_id")

);

create table failed_kpis
(
    id          integer GENERATED BY DEFAULT AS IDENTITY primary key,
    "latency"   text COLLATE pg_catalog."default",
    "threshold" text COLLATE pg_catalog."default"
    "alert_id"  integer not null,
    CONSTRAINT alert_id_fk FOREIGN KEY (alert_id)
        REFERENCES public.alerts (id)

);

create table kpi_threshold
(
    id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "test_id"   text COLLATE pg_catalog."default",
    "overlay_id" text COLLATE pg_catalog."default",
    "value" integer not null
);

INSERT into public.kpi_threshold ("test_id", "overlay_id", "value")
-- default value for all.
VALUES (null, null, 1000),
--        particular value
       ('7b659ea5-6110-4c16-b25f-b7b12886745', '0e0c6dda-95bd-4720-898a-ffe5ca819338', 5000);


ALTER TABLE IF EXISTS public.rules
    ADD CONSTRAINT "rule key" UNIQUE (rule_key);