version: '3.3'

services:

  app:
    ports:
      - "8888:8080"
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: ${IMAGE:-spirent/app}
    environment:
      - SERVER_PORT=8080
      - TIMESCALE_DB_URL=jdbc:postgresql://timescaledb:5432/db
      - USER=user
      - PASSWORD=user
      - MAX_POOL_SIZE=10

  timescaledb:
    image: 'artifactory.vwx.spirent.com/dockerhub/timescale/timescaledb:2.5.0-pg12'
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_PASSWORD=user
      - POSTGRES_USER=user
      - POSTGRES_DB=db
    volumes:
      - ./init-db.sh:/docker-entrypoint-initdb.d/init.sh